### PR TITLE
namespace VERSION as RedisRPC::VERSION

### PR DESCRIPTION
**Pull request by yaauie**
Due to a [long-standing bug in ruby-core](http://bugs.ruby-lang.org/issues/show/4156), the unnamespaced constant `VERSION` should not be overwritten. This patch namespaces the `VERSION` constant inside of `RedisRPC`, and also makes it available to code that has required RedisRPC.

### CODE REVIEW

**Comment by nfarring** [comment]
You know more Ruby than me, but with your patch I can no longer run server.rb or client.rb.

```
./server.rb
/Users/nfarring/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- redisrpc/version (LoadError)
from /Users/nfarring/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
from /Users/nfarring/src/2012/redisrpc/ruby/lib/redisrpc.rb:16:in `<top (required)>'
from ./server.rb:5:in `require_relative'
from ./server.rb:5:in `<main>'
```

**Comment by yaauie** [comment]
Ah. The gem operates under the assumption that the lib folder is included in your load-path (`$:`), but since you're running the script directly against `../lib/redisrpc.rb` without first appending to the load path (or having the gem installed), it cannot find it. Usually gem test suites explicitly add the lib folder before doing requires, but I'll submit a patch in the morning that does not make that assumption.

**Comment by yaauie** [comment]
Both now run fine under 1.8.7 and 1.9.3 for me, on an environment that only has redis and multi_json installed.

**Comment by nfarring** [comment]
Thanks! I will release a new gem soon with your patches.

**Comment by nfarring** [comment]
OK, all patches are merged and we have a new gem release on rubygems!

Nathan

On Fri, Apr 20, 2012 at 11:59 AM, Ryan Biesemeyer <
reply@reply.github.com

**Pull request merged**
