### PR TITLE
Dev/ruby gem cleanup with bundler

### PR DESCRIPTION
**Pull request by yaauie**
- a34665e1: in which I failed to isolate an unrelated commit into its own pull-request, the message is self-explanitory. Implicitly only `StandardError` (and its sub-classes) is caught; let's be explicit and catch _everything_ instead because something getting by here can be bad.
- 3d6906b0: reorganize the gemspec to be the format most gem contributors would expect. 100% of the original content is still there, but we avoid using the un-namespaced constant `DESCRIPTION`.
- 55a3950c: Use Bundler for gem/dependency management and add the associated rake tasks. This is a pre-requisite for future code, in which I'll use bundler to manage the _loading_ of gems in test/spec.

### CODE REVIEW

**Comment by nfarring** [comment]
I'm learning so much Ruby from you! For example, I didn't realize that creating variables like DESCRIPTION actually pollutes the namespace.

**Comment by nfarring** [comment]
Do Ruby folks use version tags like v0.3.5 or 0.3.5? I have been using tags like 0.3.5, but if everyone does it the other way then we can switch. I see that rake by default wants to use v0.3.5.

**Comment by yaauie** [comment]
We tend to prefix tags in git with v, but the version itself (in the gemspec) _must_ be of the format N.N.N[.A] where N is a number, A is alpha, and the square brackets indicates optional, typically for pre-release builds.

**Comment by yaauie** [comment]
Variables that start with a capital are constants, and warn when overwritten. It's a little weird like that, but once you learn it it makes reading & writing really straight-forward :)

**Pull request merged**
